const translations = {
  en: {
    logo:"logo",
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    welcome: "Welcome to our website!",
    search:"Search",
    mainHead:"Welcome , Here You Will See Every News",
    mainText:"You will find the latest world news here; all you have to do is browse.",
    categoryHeadOne:"Category One",
    categoryTextOne:"This is category one.",
    productsHead:"All Products",
    productsText:"Browse All Products , you will find your needs",
    aboutTitle: "About Us",
    aboutText: "We are a creative web solutions company specialized in building modern and scalable websites.",
    portfolio: "Portfolio",
    contact: "Contact",
    contactTitle: "Contact Us",
    phone: "Phone:",
    email: "Email:",
    address: "Address:",
    followTitle: "Follow Us",
    copy: "© 2025 My Website. All rights reserved."
  },
  ar: {
    logo: "لوجو",
    home: "الرئيسية",
    about: "من نحن",
    services: "خدماتنا",
    contact: "اتصل بنا",
    welcome: "مرحبًا بك في موقعنا!",
    search:"أبحث",
    mainHead:"أهلا بك ,سوف تجد كل الاخبار هنا",
    mainText:"سوف تجد اخر اخبار العالم هنا كل ما عليك هو التصفح",
    categoryHeadOne:"التصنيف واحد",
    categoryTextOne:"هذا نص التصنيف الاول",
    productsHead:"كل المنتجات",
    productsText:"تصفح جميع منتجاتنا وسوف تجد كل ما تحتاج",
    aboutTitle: "من نحن",
    aboutText: "نحن شركة حلول ويب إبداعية متخصصة في إنشاء مواقع حديثة وقابلة للتطوير.",
    linksTitle: "روابط سريعة",
    contact: "تواصل معنا",
    contactTitle: "تواصل معنا",
    phone: "الهاتف:",
    email: "البريد الإلكتروني:",
    address: "العنوان:",
    followTitle: "تابعنا",
    copy: "© ٢٠٢٥ جميع الحقوق محفوظة لموقعي."
  }
};
